name: Feature request
description: Ehdota ominaisuutta
labels: [enhancement]
body:
  - type: textarea
    id: need
    attributes:
      label: Tarve
      description: Mik채 ongelma tai tarve t채ll채 ratkeaa?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Ratkaisuehdotus
      description: Kuvaile toivottu toiminta
  - type: textarea
    id: notes
    attributes:
      label: Lis채tiedot